### ISSUE TITLE
Caching browser binaries

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright-github-action#10]
GHA caching docs recommend caching the NPM / Yarn cache (`~/.npm` / `yarn cache dir`), which does not have browser binaries. This means that the binaries are downloaded on every CI execution, which can be optimized. With the [@actions/tool-cache](https://github.com/actions/toolkit/tree/master/packages/tool-cache) package, this Action can potentially implement caching for binaries.

What this could look like:
- Define the `PLAYWRIGHT_BROWSERS_PATH` environment variable to specify a fixed location for the binaries to be downloaded
- Cache this location with `tc.cacheDir(dir, 'playwright-browsers', playwrightVersion)` ([docs](https://github.com/actions/toolkit/tree/master/packages/tool-cache#cache))
- Restore at the same location with `tc.find` ([docs](https://github.com/actions/toolkit/tree/master/packages/tool-cache#find))
- This would require defining `runs.post` in the action.yml, like the [actions/cache does it here](https://github.com/actions/cache/blob/4dc4b4e7582b8d269c2a98596c3fc0607209b64c/action.yml#L20). However, this bit is [not documented](https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions) in the metadata syntax reference for GHA ~(is it for some whitelisted actions only?)~
  - Verified with #11 that `runs.post` will work

Alternatively, we could achieve caching in user-land by reusing the `cache` action (this could be an MVP implementation):
- Set the `PLAYWRIGHT_BROWSERS_PATH` to a certain path, and use the same path with the `cache` action
- Use the cache action in the workflow (this will end up being duplicated, since users will have a caching action for npm/yarn already)

```yml
- name: Cache browsers
  id: cache-browsers
  uses: actions/cache@v1
  with:
    path: <same as PLAYWRIGHT_BROWSERS_PATH>
    key: key: ${{ runner.os }}-${{ hashFiles('package.json') }}
```

**Comment by aslushnikov** [comment]
> Define the PLAYWRIGHT_BROWSERS_PATH environment variable to specify a fixed location for the binaries to be downloaded

This has to be defined in user land - I think we won't be able to export env from-inside our action so that  it's used later on by clients steps. :(

Regarding the user-land setup - I'd probably cache against `package-lock.json`.

Also, do I understand correctly that those clients that already use `cache` action to cache their `node_modules/` are caching browsers as well?

**Comment by arjun27** [comment]
> Also, do I understand correctly that those clients that already use cache action to cache their node_modules/ are caching browsers as well?

No, they are not. GHA caching for npm caches the `~/.npm` directory (not node_modules) – [docs](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action).

> I think we won't be able to export env from-inside our action so that it's used later on by clients steps. :(

Looking at the [set-env command](https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable) in GHA, it is possible for actions to share environment variables (all subsequent actions after set-env can access the variable). I'll try to do this from inside the action to validate the experience.

**Comment by gilles-yvetot** [comment]
@arjunattam any success on that? Do you need help?

**Comment by mxschmitt** [comment]
Currently its not planned to cache browser's. It's different on each language binding and depends on the version. 

If you still want caching, you can do it manually with https://github.com/actions/cache
A
Cache key: playwright version (or whole file e.g. package.json, requirements.txt etc.)
Cache folder: https://playwright.dev/docs/browsers#managing-browser-binaries

As written above, this can be also leveraged using the `PLAYWRIGHT_BROWSERS_PATH` environment variable.

**Comment by jesstelford** [comment]
For caching binaries on GitHub Actions, see https://github.com/microsoft/playwright/issues/7249#issuecomment-1154603556

_(Sorry for the zombie post; this issue comes in as the top result when searching for `Playwright cache binaries`, and I wanted to point weary travellers [such as my future self] in the right direction)_
