### ISSUE TITLE
JavaScript not executing

### ISSUE THREAD

**Issue by FezVrasta** [microsoft/playwright-github-action#14]
Hi, I'm sorry to open a PR without much details but I don't know where to look anymore.

The tests in this PR keep failing because JS seems to not run at all, while when I run them locally they execute just fine (1 of them is failing but it's unrelated).

https://github.com/popperjs/popper-core/pull/990

Do you have any hint?

**Comment by yury-s** [comment]
Can you provide some details on the remote environment where the tests are failing? Also it'd be helpful if you could add `DEBUG=pw:browser` before the `npm run test` command to see if the browser can start at all and post the output here.

**Comment by FezVrasta** [comment]
The actions config is here:
https://github.com/popperjs/popper-core/blob/test/playwright/.github/workflows/functional-tests.yml

I enabled the logs, these are the logs for Chrome:
https://github.com/popperjs/popper-core/pull/990/checks?check_run_id=630198778

**Comment by yury-s** [comment]
[This pixel diff](https://anonymousfiles.io/f/prevent-overflow-test-js-should-not-overflow-when-small-reference-is-at-edge-of-boundary_ggNlnfS.png) looks odd. It seems that scrolling didn't happen but I cannot make sense of the stray red square at the top left corner. Are they re-positioned separately?

**Comment by FezVrasta** [comment]
the red square is the diff

**Comment by yury-s** [comment]
Sorry, I meant `<div id="reference"></div>` from edge.html which is positioned quite far away from 'Popper box' on the actual result (the right hand side of the diff png). When I run it locally with `HEADLESS=false` all 3 boxes move together, so the layout on the bot seems broken to me or is it fine?

**Comment by yury-s** [comment]
I checked out https://github.com/popperjs/popper-core/tree/test/playwright and all the tests pass locally for me. I noticed though that with HEADLESS=false they start failing because in headful mode we do show scroll bars while in headless they are invisible. This seems like a bug in playwright. But I doubt it has anything to do with your problem. Looking at the layout difference I asked above my hunch is that there may be some differences in how `overflow: scroll` is being handled on CI, I've no idea what difference with the local environment could cause that, will keep looking.

**Comment by FezVrasta** [comment]
There shouldn't be any differences. Thanks for looking into this!

**Comment by FezVrasta** [comment]
> When I run it locally with HEADLESS=false all 3 boxes move together, so the layout on the bot seems broken to me or is it fine?

I'm not sure what you mean, Popper is meant to stick elements close to each other, even during scroll, if that's what you see that's the expected behavior.

**Comment by yury-s** [comment]
I'm talking about this ![screenshot](https://user-images.githubusercontent.com/9798949/80648601-49838300-8a25-11ea-9617-119a14df09fb.png), I cannot reproduce such layout locally.

**Comment by FezVrasta** [comment]
Probably that’s the test that should hide the arrow (the red square) when it goes outside the boundaries. But without JavaScript that doesn’t happen

**Comment by yury-s** [comment]
It was from 'should not overflow when small reference is at edge of boundary'.

**Comment by FezVrasta** [comment]
This is how it should look like


https://github.com/popperjs/popper-core/blob/master/tests/functional/__image_snapshots__/prevent-overflow-test-js-should-not-overflow-when-small-reference-is-at-edge-of-boundary-1-snap.png?raw=true

**Comment by yury-s** [comment]
Oh, I see now what you mean, sorry it took a while. Based on what you described and given that the problem is consistent across all 3 browsers I suspect that it may be that some of the links get broken on CI:
```js
  import { createPopper } from '../../dist/popper.js';
```
can you check if that's the case by a chance?

**Comment by yury-s** [comment]
@FezVrasta try adding the following to the failing tests to see if there is any problem with the resource loading that would produce console output:
```js
beforeAll(() => {
  page.on('console', m => console.log('Console message: ' + m.text() + '; URL: ' + page.url()));
});
```

**Comment by FezVrasta** [comment]
![image](https://user-images.githubusercontent.com/5382443/80802045-71522280-8bae-11ea-95b0-f23c5532e8d1.png)

You are right about the resource loading issue, but I'm not sure what am I doing wrong to provoke this...

**Comment by FezVrasta** [comment]
Woah ok... I'm an idiot, at some point I removed the step that builds the assets on CI... Thank you for your help 😭

**Comment by yury-s** [comment]
Awesome! Glad that I could help. We should probably add some recommendations like this into debugging/troubleshooting section.

**Comment by TomasHubelbauer** [comment]
This is the Google top hit for JavaScript not executing so I will add my own experience: I was testing a page running off the `file:` protocol and my script wasn't executing because of CORS on the `file:` protocol. I had to add this to my project in `playwright.config.ts`:

```js
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        launchOptions: {
          args: ['--disable-web-security'],
        }
```
