### ISSUE TITLE
Windows media pack

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright-github-action#23]
Following https://github.com/microsoft/playwright/pull/3137. We could update the readme for usage instructions on `windows-latest`

**Comment by yury-s** [comment]
Sure, I will update it as soon as we figure out what actually needs to be installed as that patch didn't quite work out (our video capability test still fails on the bot while passing locally).

**Comment by mxschmitt** [comment]
Added in https://github.com/microsoft/playwright/pull/6836
