### ISSUE TITLE
Canvases using WebGL not loading

### ISSUE THREAD

**Issue by oh-wo** [microsoft/playwright-github-action#49]
Hi there,

We love playwright and think you've done a great job so thanks very much for that!

- We've found that with `headless: false` we are not getting WebGl through, a 3rd party canvas library throws the error `Error: WebGL unsupported in this browser`.
- Further recorded via video recording.
- It all works fine locally, however.

Is there anyway to workaround this issue?

### Github action run command
```
xvfb-run yarn --cwd ui e2e
```
### package.json
```json
{
   ...,
   "scripts": {
      "e2e": "jest --config ./e2e/jest.config.js",
   },
   ...,
}
```

### Spec file
```
browser = await chromium.launch({
      headless: false,
});
context = await browser.newContext({
bypassCSP: true,
recordHar: {
  path: '/tmp/e2e-har-recordings',
},
recordVideo: {
  dir: '/tmp/e2e-video-recordings',
},
});
page = await context.newPage();
```

**Comment by mxschmitt** [comment]
Sorry for the late reply, please open an issue in the Playwright repository: https://github.com/microsoft/playwright/issues
