### ISSUE TITLE
How to cache Playwright installation?

### ISSUE THREAD

**Issue by edpichler** [microsoft/playwright-github-action#56]
It's currently by far the slowest step of my pipeline. It takes more than one minute to install it, in every build. 

![image](https://user-images.githubusercontent.com/358696/150648833-bce0f960-8201-424f-abe7-fcd94c1f00fb.png)

PS: The `actions/setup-node@v2` action has cache. It takes only a few seconds to complete.

**Comment by mxschmitt** [comment]
This Playwright Action as well as `npx playwright install-deps` does install system dependencies. It's not possible to cache system dependencies on GitHub Actions. If you want to have them before running your tests, you can e.g. use the official Docker image with GitHub Actions. See here for reference:

- https://playwright.dev/docs/docker
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-running-a-job-within-a-container

For GitHub Actions specifying the container image should run the steps inside the Docker container.

**Comment by edpichler** [comment]
Got it. Thank you @mxschmitt
