### ISSUE TITLE
Protocol error (Playwright.createContext): Browser has been closed.

### ISSUE THREAD

**Issue by FezVrasta** [microsoft/playwright-github-action#6]
I'm encountering the error `Protocol error (Playwright.createContext): Browser has been closed.` when I try to run WebKit on my repository.

https://github.com/popperjs/popper-core/pull/990#issuecomment-611927078

I'm using jest-playwright-preset

**Comment by arjun27** [comment]
Hi @fezvrasta, I noticed that the PR builds ([like this](https://github.com/popperjs/popper-core/runs/576988088)) after the upgrade to Playwright 0.13.0 don't have this error. Were you able to make it work with the newer Playwright version?

**Comment by FezVrasta** [comment]
Hi, I didn't notice the update fixed it, I'll close this then, thanks!
