### ISSUE TITLE
 To enable the performance trace for a playwright functional scripts

### ISSUE THREAD

**Issue by rabindraqa** [microsoft/playwright-github-action#77]

**Comment by rabindraqa** [comment]
Can we have config where we can enable performance trace for all the scripts.
await context.tracing.start({ screenshots: true, snapshots: true });
await context.tracing.stop({ path: 'trace.zip' });

**Comment by mxschmitt** [comment]
This repository is not intended for filing bugs for the Playwright project, I recommend filing it [here](http://github.com/microsoft/playwright) and following the bug template.
