### ISSUE TITLE
Missing libraries for webkit browsers (libwoff2dec.so)

### ISSUE THREAD

**Issue by adamchemiawppl** [microsoft/playwright-github-action#83]
My tests fail with webkit browsers (same tests on local system work just fine)

Relevant part of error log:

<launching> /home/runner/.cache/ms-playwright/webkit-1992/pw_run.sh --inspector-pipe --headless --no-startup-window
    <launched> pid=1992
    [pid=1992][err] /home/runner/.cache/ms-playwright/webkit-1992/minibrowser-wpe/bin/MiniBrowser: error while loading shared libraries: libwoff2dec.so.1.0.2: cannot open shared object file: No such file or directory
    [pid=1992] <process did exit: exitCode=127, signal=null>
    [pid=1992] starting temporary directories cleanup
    Call log:
      - <launching> /home/runner/.cache/ms-playwright/webkit-1992/pw_run.sh --inspector-pipe --headless --no-startup-window
      - <launched> pid=1992
      - [pid=1992][err] /home/runner/.cache/ms-playwright/webkit-1992/minibrowser-wpe/bin/MiniBrowser: error while loading shared libraries: libwoff2dec.so.1.0.2: cannot open shared object file: No such file or directory
      - [pid=1992] <process did exit: exitCode=127, signal=null>
      - [pid=1992] starting temporary directories cleanup

**Comment by mxschmitt** [comment]
Please file an issue here and follow the issue template: https://github.com/microsoft/playwright/issues/new?assignees=&labels=&projects=&template=bug.yml&title=%5BBug%5D%3A+
